### ISSUE TITLE
User Status

### ISSUE THREAD

**Issue by antkarag13** [Shadow-Creation-Team/Protector#15] opened 2021-03-13 20:06 UTC
**Describe the bug**
User's Status is not the right.

**Expected behavior**
It has to show do not distruct.

**Solution**
![Screenshot_91](https://user-images.githubusercontent.com/71717457/111042897-44b29c80-8448-11eb-8805-67aec8814743.png)
Turn them on. I did it to my bot and it works fine.

**Screenshots**
![Screenshot_89](https://user-images.githubusercontent.com/71717457/111042855-146afe00-8448-11eb-9f59-16b0823788b9.png)
![Screenshot_90](https://user-images.githubusercontent.com/71717457/111042867-2187ed00-8448-11eb-88b4-cd1e52377569.png)

**Comment by Tougrel** [comment] 2021-03-13 20:13
This is a known issue caused by the **Privileged Intents**. The problem here is that discord denied us access because info like that are available on the client. Developers **CAN'T** enable intents without applying for them, so we won't work on this for now but we will keep it in mind once the dashboard is up and the presence intent is enabled it will be fixed ;)

**Closed by Tougrel** 2021-03-13 20:13 UTC
Labels: bug, discord, wontfix
